# Generated by Django 3.0.5 on 2020-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('channel', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('view_count', models.BigIntegerField()),
                ('like_count', models.BigIntegerField()),
                ('dislike_count', models.BigIntegerField()),
                ('favorite_count', models.BigIntegerField()),
                ('comment_count', models.BigIntegerField()),
                ('comment_sentiment', models.FloatField()),
                ('published_at', models.DateTimeField()),
                ('duration', models.BigIntegerField()),
            ],
        ),
    ]
